# Generated by Django 4.1.7 on 2023-02-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('No_of_guests', models.PositiveIntegerField(default=1)),
                ('BookingDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
